extends SceneTree

const TerrainResource = preload("res://scripts/prototypes/ember_terrain_pilot_resource.gd")
const Diagnostics = preload("res://addons/ember_import/ember_terrain_diagnostics.gd")
const CompactBrush = preload("res://addons/ember_import/ember_compact_terrain_brush.gd")


func _initialize() -> void:
	call_deferred("_run")


func _run() -> void:
	var source := TerrainResource.new()
	source.width = 128
	source.depth = 128
	source.palette = PackedColorArray([Color.TRANSPARENT, Color.BROWN, Color.GREEN])
	var count := source.width * source.depth
	source.heights.resize(count)
	source.heights.fill(8)
	source.top_materials.resize(count)
	source.top_materials.fill(2)
	source.base_materials.resize(count)
	source.base_materials.fill(1)
	source.cap_depths.resize(count)
	source.cap_depths.fill(3)
	source.water_levels.resize(count)
	source.water_materials.resize(count)
	var original := source.heights.duplicate()
	var warning_map := EmberMapLoader.new()
	warning_map.hydrate_legacy_regions = false
	warning_map.authored_size_blocks = Vector2i(8, 8)
	warning_map.compact_terrain = source
	warning_map.editor_warning_timing_enabled = true
	assert(warning_map._get_configuration_warnings().is_empty())
	assert(warning_map.editor_warning_validation_count == 1)
	assert(warning_map.editor_warning_validation_usec >= 0)
	warning_map.free()
	var projection := EmberTerrainPilotProjection.new()
	projection.source = source
	root.add_child(projection)
	while projection.pending_tile_count() > 0:
		await process_frame
	var before := projection.profile_snapshot()
	assert(int(before.tile_builds) == 4 and int(before.ground_vertices) > 0)
	assert(int(before.geometry_us) > 0 and int(before.mesh_resource_us) > 0)
	assert(int(before.collision_shape_us) > 0 and int(before.collision_attach_us) > 0)
	var report: Dictionary = await Diagnostics.capture(self, root, projection, 6)
	assert(report.context == "editor_viewport_3d")
	assert(report.viewport.has("visible_draw_calls_median"))
	assert(report.viewport.has("render_gpu_ms_median"))
	assert(report.terrain == before)
	var path: String = Diagnostics.save_report(report)
	assert(not path.is_empty() and FileAccess.file_exists(path))
	var decoded: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(path))
	assert(decoded.schema == 1 and int(decoded.terrain.tile_builds) == 4)
	assert(source.heights == original)
	assert(projection.document.heights == original)
	assert(projection.pending_tile_count() == 0)
	var recorder := Diagnostics.new()
	assert(recorder.start_brush_recording({"map_id": "hover_fixture"}, root, projection))
	recorder.record_hover({"cell": [64, 64], "pick_usec": 120, "grid": {"tiles_rebuilt": 1}})
	await process_frame
	var hover_report: Dictionary = recorder.stop_brush_recording()
	assert(hover_report.strokes.is_empty() and hover_report.hovers.size() == 1)
	assert(int(hover_report.hovers[0].pick_usec) == 120)
	assert(int(hover_report.hovers[0].grid.tiles_rebuilt) == 1)
	assert(source.heights == original and projection.document.heights == original)
	assert(recorder.start_brush_recording({"map_id": "late_freeze_fixture"}, root, projection))
	for i in Diagnostics.MAX_RECORDED_HOVERS + 2:
		recorder.record_hover({"event": i})
	var late_report: Dictionary = recorder.stop_brush_recording()
	assert(late_report.truncated_hovers == 2)
	assert(late_report.hovers.front().event == 2)
	assert(late_report.hovers.back().event == Diagnostics.MAX_RECORDED_HOVERS + 1)
	assert(recorder.start_brush_recording({"map_id": "diagnostic_fixture"}, root, projection))
	recorder.begin_brush_stroke({"mode": "raise", "radius_blocks": 8.0})
	recorder.record_editor_process(1500)
	recorder.record_dirty_status(800)
	recorder.stage("brush_collect", 1200)
	recorder.stage("resource_write", 300)
	recorder.brush_step("first", 1500, 64, 1)
	await process_frame
	recorder.finish_brush_stroke(64)
	recorder._record_editor_frame()
	var recorded: Dictionary = recorder.stop_brush_recording()
	assert(not recorder.recording and recorded.schema == "ember-compact-brush-trace-v1")
	assert(recorded.strokes.size() == 1 and recorded.strokes[0].steps.size() == 1)
	assert(int(recorded.strokes[0].stages_usec.brush_collect) == 1200)
	assert(int(recorded.strokes[0].changed_columns) == 64)
	assert(recorded.metadata.map_id == "diagnostic_fixture")
	assert(recorded.final_terrain.pending_tiles == 0)
	assert(recorded.final_terrain.has("coalesced_tile_requests"))
	assert(recorded.frames.back().has("since_last_release_usec"))
	assert(int(recorded.frames.back().since_last_release_usec) >= 0)
	assert(recorded.frames.back().has("max_pending_age_usec"))
	assert(int(recorded.frames.back().editor_process_usec) == 1500)
	assert(int(recorded.frames.back().dirty_status_usec) == 800)
	assert(int(recorded.frames.back().dirty_status_count) == 1)
	assert(recorded.frames.back().has("warning_validation_count"))
	var brush_report_path: String = Diagnostics.save_report(recorded)
	assert(not brush_report_path.is_empty() and FileAccess.file_exists(brush_report_path))
	var brush_decoded: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(brush_report_path))
	assert(brush_decoded.strokes[0].steps[0].kind == "first")
	assert(source.heights == original and projection.document.heights == original)
	var owner := Node3D.new()
	var undo := UndoRedo.new()
	var brush := CompactBrush.new()
	brush.configure({"target": weakref(owner), "resource": source}, undo, owner)
	assert(recorder.start_brush_recording({"map_id": "brush_fixture"}, root, projection))
	recorder.begin_brush_stroke({"mode": "raise", "radius_blocks": 1.0})
	assert(brush.begin("raise", 1.0, 4, 2, 0, 16, 0, 371, 0, -99999, "coarse"))
	brush.diagnostic_sink = recorder
	var stamp_started := Time.get_ticks_usec()
	brush.stamp(Vector2i(64, 64))
	recorder.brush_step("first", Time.get_ticks_usec() - stamp_started, brush.changed_column_count(), 0)
	var changed := brush.changed_column_count()
	brush.end()
	brush.diagnostic_sink = null
	recorder.finish_brush_stroke(changed)
	var actual_brush_report := recorder.stop_brush_recording()
	assert(changed > 0 and actual_brush_report.strokes[0].stages_usec.has("brush_collect"))
	assert(actual_brush_report.strokes[0].stages_usec.has("resource_write"))
	assert(actual_brush_report.strokes[0].stages_usec.has("undo_snapshot"))
	assert(actual_brush_report.strokes[0].stages_usec.has("history_commit"))
	assert(actual_brush_report.strokes[0].steps[0].changed_columns == changed)
	undo.undo()
	assert(source.heights == original and projection.document.heights == original)
	undo.clear_history()
	undo.free()
	owner.free()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	DirAccess.remove_absolute(ProjectSettings.globalize_path(brush_report_path))
	projection.free()
	print("TERRAIN_DIAGNOSTICS read_only=ok report=ok stages=ok viewport_counters=ok brush_recorder=ok actual_brush=ok")
	quit()
